apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: mongodb
  name: mongodb
  namespace: acme-air-knot
spec:
  clusterIP: None
  ports:
  - name: connection-port
    port: 27017
    protocol: TCP
    targetPort: connection-port
  selector:
    app: mongodb
  sessionAffinity: None
  type: ClusterIP
