apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frisk-api
  name: frisk-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frisk-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frisk-api
    spec:
      affinity: {}
      containers:
        - name: frisk-api
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: ELASTIC_HOST
              value: elasticsearch-logging
            - name: ELASTIC_PORT
              value: '9200'
          image: garreeoke/frisk:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-port
              protocol: TCP
          resources: {}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File